### ISSUE TITLE
Game crashed when playing

### ISSUE THREAD

**Issue by Pgasus9412** [ZengineeringTeam/Zengineering#14]
正常游玩过程中突然出现中心放射状黑色块，有些时候出现该现象后游戏立即崩溃，有些时候色块过一会后自然消失
使用HMCL 3.3.180启动器 整合包版本1.1.4 Forge版本31.2.47 Optifine版本HD_U_G6_pre5
自行额外添加的mod有：
FastFurance-1.15.1-3.0.0
TorchBowMod_v1.5
immersive-portals-0.24forMc1.15withForge
附：出现色块时的游戏截图和崩溃报告
![崩溃](https://user-images.githubusercontent.com/78341779/106426329-42592d80-641a-11eb-91f5-273be20dcbaa.png)
[minecraft-exported-logs-2021-02-01T15-09-21.log](https://github.com/ZengineeringTeam/Create-101/files/5902405/minecraft-exported-logs-2021-02-01T15-09-21.log)

**Comment by Snownee** [comment]
装Optifine的话不要装JourneyMap
