### ISSUE TITLE
机械动力组件不显示数字等

### ISSUE THREAD

**Issue by Dirt030** [ZengineeringTeam/Zengineering#20]
所有组件都无法显示数字，例如变速箱不显示转速，轴承不显示连接范围等
最新版本，从第二次打开游戏开始发生这种问题
![2021-03-08_22 04 26](https://user-images.githubusercontent.com/44526536/110331611-4cde9680-805a-11eb-90d7-ce6c49687119.png)

**Comment by Snownee** [comment]
调整画质
