### ISSUE TITLE
Server botany pots not working correctly

### ISSUE THREAD

**Issue by SquangeEj** [ZengineeringTeam/Zengineering#22]
The custom botany pots do not work in a server, they revert back to the original non custom crafts e.g coral giving coral, it not accepting iron and stone

**Comment by Snownee** [comment]
I think that is probably because you don't install the server pack correctly

**Comment by SquangeEj** [comment]
I transferred the libraries, mods, config and defaultconfigs (alongside doing without defaultconfigs but nothing changes) and the jar file with renamed forge, im unsure if im missing a file because the server runs just not the pots custom data

**Comment by Snownee** [comment]
openloader folder?

**Comment by SquangeEj** [comment]
That fixes it thank you :) tutorial only showed 3 folders
