### ISSUE TITLE
服务器开启了，但是进不去

### ISSUE THREAD

**Issue by DancingSnow0517** [ZengineeringTeam/Zengineering#26]
![image](https://user-images.githubusercontent.com/60736156/115114734-695be000-9fc3-11eb-8c1e-6463ad109efa.png)
![image](https://user-images.githubusercontent.com/60736156/115114736-6d87fd80-9fc3-11eb-9617-cd394ca2096d.png)
![image](https://user-images.githubusercontent.com/60736156/115114745-77116580-9fc3-11eb-8c99-b9b5930d2aa0.png)

**Comment by Snownee** [comment]
版本不匹配？
