### ISSUE TITLE
create漏斗类物品放不进抽屉

### ISSUE THREAD

**Issue by Night-Aurora** [ZengineeringTeam/Zengineering#27]
![4 2QRVCSJ_PNY} D17JQXKO](https://user-images.githubusercontent.com/69863306/116771000-83dd9100-aa7a-11eb-8036-c3efdea99c71.png)

![SY8D{929AN7CI{Q6 C3D9VS](https://user-images.githubusercontent.com/69863306/116770999-817b3700-aa7a-11eb-928c-5154d0eddcbb.png)

**Comment by Snownee** [comment]
用管道

**Comment by Night-Aurora** [comment]
什么mod的管道？搜到的管道都做不出来

**Comment by Snownee** [comment]
任何能传输物品的东西
