### ISSUE TITLE
Incompatible Modlist

### ISSUE THREAD

**Issue by 1ECS** [ZengineeringTeam/Zengineering#28]
Cannot connect to server due to incompatible fml modlist

**Comment by Quezler** [comment]
can confirm:

![Screen Shot 2021-06-01 at 11 30 50](https://user-images.githubusercontent.com/3179271/120301153-deae1680-c2cc-11eb-8695-73792b97c7ed.png)
![Screen Shot 2021-06-01 at 11 30 56](https://user-images.githubusercontent.com/3179271/120301156-df46ad00-c2cc-11eb-8ec6-67d887b3e1f0.png)

**Comment by Snownee** [comment]
I hope I have fixed it in 2.2.3
