### ISSUE TITLE
服务端无法长时间运行，一段时间会崩

### ISSUE THREAD

**Issue by Night-Aurora** [ZengineeringTeam/Zengineering#29]
crash-report：
[crash-2021-05-29_01.43.49-server.txt](https://github.com/ZengineeringTeam/Create-101/files/6593039/crash-2021-05-29_01.43.49-server.txt)

**Comment by Snownee** [comment]
试试更新Create

**Comment by Night-Aurora** [comment]
> 试试更新Create

顺便问一个问题，最近发现挖掉的泥土不会自动更新为草方块了，好像是从2.2.1（Server）版本开始就出现了之前版本没有，是最新版本把草地更新禁掉了吗？
![02 31N%_`V0%8AE~AZ2)DHS](https://user-images.githubusercontent.com/69863306/120898487-a48e9d00-c65d-11eb-8cf0-4ea83a0ca4a5.png)

**Comment by Snownee** [comment]
没有
