### ISSUE TITLE
suggestion: show which advancements reward what

### ISSUE THREAD

**Issue by Quezler** [ZengineeringTeam/Zengineering#31]
currently you just get item rewards "unexpectedly" and "out of nowhere" when you happen to complete advancements.

on my first (and to date only) playthrough of this pack with a bunch of friends it has occasionally happened that you complete an advancement some time after another player in the base has completed it, and by the time you happen to randomly pickup the item to unlock it you might have already crafted the reward item yourself.

for this reason it would be neat if the item rewarded is listed in the description of the advancement when you hover over it or something, to give players some insight in "oh if i want this item i can either craft it, or complete that specific advancement.

either way: love the pack, my 2nd play through is due soon, and in light of that i have decided to post this here, for science. 🙂

**Comment by Snownee** [comment]
Thank you for your suggestion. But I don't have plan to change it, the intention of rewards is giving the pack a few surprises, and it won't affect the progression too much. So I will just keep this
