### ISSUE TITLE
Can't turn off walking sounds or switching in hotbar sounds

### ISSUE THREAD

**Issue by freerk92** [ZengineeringTeam/Zengineering#38]
The only way to turn them off, is by turning the Master Volume to 0.
I still want to hear mobs, I just don't want to hear the walking and hotbar switching sounds.

**Comment by Snownee** [comment]
I think it is DynamicSurroundings

**Comment by freerk92** [comment]
Found the settings for DynamicSurroundings and that fixed it.
Thank you so much, the sounds were driving me crazy :P
