### ISSUE TITLE
RS存储方块/磁盘数据丢失

### ISSUE THREAD

**Issue by zzx517** [ZengineeringTeam/Zengineering#39]
在我的一个存档里，在磁盘驱动器中放入存储磁盘，或连接一个存储方块，保存退出存档。重新加载存档后，磁盘驱动器中的存储磁盘会消失，存储方块里存储的物品会消失。已发生多次，没有例外。
此现象仅在我的一个特定的存档发生，别的存档未能复现。

**Comment by zzx517** [comment]
整合包版本2.2.3

**Comment by Snownee** [comment]
尝试移除区块加载器

https://github.com/refinedmods/refinedstorage/issues/3130

**Comment by zzx517** [comment]
是Chunk Loader的区块加载器的问题，谢谢！Thank you very much!
