### ISSUE TITLE
服务端无法启动

### ISSUE THREAD

**Issue by bochennnn** [ZengineeringTeam/Zengineering#40]
如题，服务端启动不了，刚打开就退出，版本为2.2.3,java版本1.8.0_333这是日志
[latest.log](https://github.com/ZengineeringTeam/Create-101/files/9711959/latest.log)
[debug.log](https://github.com/ZengineeringTeam/Create-101/files/9711961/debug.log)

**Comment by Snownee** [comment]
Java版本太高

**Comment by bochennnn** [comment]
那什么版本合适

**Comment by Snownee** [comment]
u321之前

**Comment by bochennnn** [comment]
谢谢
